export const mockScholarships = [
  {
    id: 1,
    Name: "Pre-Matric Scholarship",
    Benefits: "Tuition, books, educational expenses",
    link: "https://scholarship.mp.gov.in/Public/MaleSchemes/GB.aspx?ID=MTE=",
    Gender: "All",
    Cast: "All",
    EducationLevel: "School",
  },
  {
    id: 2,
    Name: "Pre-Matric Scholarship",
    Benefits: "Tuition, academic expenses, maintenance",
    link: "https://scholarship.mp.gov.in/Public/MaleSchemes/GB.aspx?ID=MTE=",
    Gender: "Male",
    Cast: "General",
    EducationLevel: "School",
  },
  {
    id: 3,
    Name: "Dashmottar Scholarship",
    Benefits: "Academic fees, living expenses",
    link: "https://scholarship.mp.gov.in/Public/MaleSchemes/GB.aspx?ID=MTE=",
    Gender: "Female",
    Cast: "General",
    EducationLevel: "Schoole",
  },
  {
    id: 4,
    Name: "NMMSS",
    Benefits: "Rs. 12,000 per annum",
    link: "https://scholarships.gov.in/",
    Gender: "Female",
    Cast: "All",
    EducationLevel: "School",
  },
  {
    id: 5,
    Name: "State Merit Scholarship",
    Benefits: "Tuition and Academic fees",
    link: "",
    Gender: "All",
    Cast: "All",
    EducationLevel: "School",
  },
  {
    id: 6,
    Name: "Minority Scholarship",
    Benefits: "Tuition, Maintenance",
    link: "https://scholarship.mp.gov.in/Public/MaleSchemes/GB.aspx?ID=MTE=",
    Gender: "All",
    Cast: "ST",
    EducationLevel: "Postgraduate",
  },
  {
    id: 7,
    Name: "Scholarship for Disabled Students",
    Benefits: "Tuition, books, equipment",
    link: "https://scholarship.mp.gov.in/Public/MaleSchemes/GB.aspx?ID=MTE=",
    Gender: "Male",
    Cast: "SC",
    EducationLevel: "Postgraduate",
  },
  {
    id: 8,
    Name: "Chief Minister's Fellowship",
    Benefits: "Monthly Stipend, Tuition Fee waiver",
    link: "Official Portal",
    Gender: "Male",
    Cast: "OBC",
    EducationLevel: "Diploma",
  },
  {
    id: 9,
    Name: "Eklavya Scholarship",
    Benefits: "Financial Assistance for higher education",
    link: "https://scholarship.mp.gov.in/Public/MaleSchemes/GB.aspx?ID=MTE=",
    Gender: "Male",
    Cast: "ST",
    EducationLevel: "Higher Education",
  },
  {
    id: 10,
    Name: "Post-Matric Scholarship",
    Benefits: "Tuition and maintenance",
    link: "https://scholarship.mp.gov.in/Public/MaleSchemes/GB.aspx?ID=MTE=",
    Gender: "Female",
    Cast: "General",
    EducationLevel: "Postgraduate",
  },
  {
    id: 11,
    Name: "Scholarship for SC Students",
    Benefits: "Academic fees and living expenses",
    link: "https://scholarship.mp.gov.in/Public/MaleSchemes/GB.aspx?ID=MTE=",
    Gender: "Male",
    Cast: "SC",
    EducationLevel: "Undergraduate",
  },
  {
    id: 12,
    Name: "National Scholarship Scheme",
    Benefits: "Tuition fees, maintenance allowance",
    link: "https://scholarship.gov.in/",
    Gender: "Male",
    Cast: "OBC",
    EducationLevel: "Diploma",
  },
  {
    id: 13,
    Name: "Merit-Based Scholarship",
    Benefits: "Financial aid for tuition",
    link: "https://scholarship.mp.gov.in/Public/MaleSchemes/GB.aspx?ID=MTE=",
    Gender: "All",
    Cast: "All",
    EducationLevel: "Postgraduate",
  },
  {
    id: 14,
    Name: "State Government Scholarship",
    Benefits: "Tuition, books, educational allowance",
    link: "https://scholarship.gov.in/",
    Gender: "Female",
    Cast: "General",
    EducationLevel: "Undergraduate",
  },
  {
    id: 15,
    Name: "Research Fellowship",
    Benefits: "Stipend, tuition fee waiver",
    link: "https://scholarships.gov.in/",
    Gender: "Male",
    Cast: "SC",
    EducationLevel: "Higher Education",
  },
  {
    id: 16,
    Name: "National Merit Scholarship",
    Benefits: "Books, tuition fees",
    link: "https://scholarship.mp.gov.in/Public/MaleSchemes/GB.aspx?ID=MTE=",
    Gender: "Female",
    Cast: "OBC",
    EducationLevel: "School",
  },
  {
    id: 17,
    Name: "Science Scholarship",
    Benefits: "Research funding and tuition",
    link: "https://scholarships.gov.in/",
    Gender: "Male",
    Cast: "ST",
    EducationLevel: "Postgraduate",
  },
  {
    id: 18,
    Name: "Engineering Scholarship",
    Benefits: "Tuition fee and stipend",
    link: "https://scholarship.mp.gov.in/Public/MaleSchemes/GB.aspx?ID=MTE=",
    Gender: "Female",
    Cast: "All",
    EducationLevel: "Undergraduate",
  },
  {
    id: 19,
    Name: "Law Scholarship",
    Benefits: "Tuition and living allowance",
    link: "https://scholarship.mp.gov.in/Public/MaleSchemes/GB.aspx?ID=MTE=",
    Gender: "Male",
    Cast: "General",
    EducationLevel: "Postgraduate",
  },
  {
    id: 20,
    Name: "Medical Scholarship",
    Benefits: "Tuition, books, and medical supplies",
    link: "https://scholarship.mp.gov.in/Public/MaleSchemes/GB.aspx?ID=MTE=",
    Gender: "Male",
    Cast: "OBC",
    EducationLevel: "Undergraduate",
  },
  {
    id: 21,
    Name: "Education Loan Scholarship",
    Benefits: "Loan for tuition fees",
    link: "https://scholarships.gov.in/",
    Gender: "Female",
    Cast: "ST",
    EducationLevel: "Diploma",
  },
  {
    id: 22,
    Name: "Arts Scholarship",
    Benefits: "Tuition fees, living expenses",
    link: "https://scholarship.mp.gov.in/Public/MaleSchemes/GB.aspx?ID=MTE=",
    Gender: "Male",
    Cast: "SC",
    EducationLevel: "Undergraduate",
  },
  {
    id: 23,
    Name: "Research Grant",
    Benefits: "Funding for research projects",
    link: "https://scholarships.gov.in/",
    Gender: "Female",
    Cast: "OBC",
    EducationLevel: "Higher Education",
  },
  {
    id: 24,
    Name: "Women Empowerment Scholarship",
    Benefits: "Tuition, mentorship",
    link: "https://scholarship.mp.gov.in/Public/MaleSchemes/GB.aspx?ID=MTE=",
    Gender: "Female",
    Cast: "All",
    EducationLevel: "Postgraduate",
  },
  {
    id: 25,
    Name: "International Study Scholarship",
    Benefits: "Funding for study abroad",
    link: "https://scholarships.gov.in/",
    Gender: "Male",
    Cast: "General",
    EducationLevel: "Higher Education",
  },
  {
    id: 26,
    Name: "State Development Scholarship",
    Benefits: "Tuition and educational expenses",
    link: "https://scholarship.mp.gov.in/Public/MaleSchemes/GB.aspx?ID=MTE=",
    Gender: "All",
    Cast: "ST",
    EducationLevel: "Diploma",
  },
  {
    id: 27,
    Name: "Environmental Studies Scholarship",
    Benefits: "Books, tuition fees",
    link: "https://scholarships.gov.in/",
    Gender: "Female",
    Cast: "All",
    EducationLevel: "Postgraduate",
  },
  {
    id: 28,
    Name: "Music Scholarship",
    Benefits: "Tuition and performance grant",
    link: "https://scholarships.gov.in/",
    Gender: "Male",
    Cast: "OBC",
    EducationLevel: "School",
  },
  {
    id: 29,
    Name: "History Scholarship",
    Benefits: "Books, tuition fees",
    link: "https://scholarship.mp.gov.in/Public/MaleSchemes/GB.aspx?ID=MTE=",
    Gender: "Male",
    Cast: "SC",
    EducationLevel: "Postgraduate",
  },
  {
    id: 30,
    Name: "Technology Scholarship",
    Benefits: "Tuition, tech equipment",
    link: "https://scholarships.gov.in/",
    Gender: "Male",
    Cast: "ST",
    EducationLevel: "Undergraduate",
  },
  {
    id: 31,
    Name: "Medical Research Scholarship",
    Benefits: "Stipend, research funding",
    link: "https://scholarships.gov.in/",
    Gender: "Female",
    Cast: "OBC",
    EducationLevel: "Postgraduate",
  },
  {
    id: 32,
    Name: "Agricultural Scholarship",
    Benefits: "Tuition and research funding",
    link: "https://scholarships.gov.in/",
    Gender: "Male",
    Cast: "General",
    EducationLevel: "School",
  },
  {
    id: 33,
    Name: "Business Scholarship",
    Benefits: "Tuition and books",
    link: "https://scholarships.gov.in/",
    Gender: "All",
    Cast: "ST",
    EducationLevel: "Diploma",
  },
  {
    id: 34,
    Name: "Management Scholarship",
    Benefits: "Tuition and internship allowance",
    link: "https://scholarships.gov.in/",
    Gender: "Female",
    Cast: "SC",
    EducationLevel: "Postgraduate",
  },
  {
    id: 35,
    Name: "Sports Scholarship",
    Benefits: "Tuition and sports allowance",
    link: "https://scholarships.gov.in/",
    Gender: "Male",
    Cast: "OBC",
    EducationLevel: "Undergraduate",
  },
  {
    id: 36,
    Name: "Scholarship for Visually Impaired",
    Benefits: "Tuition, books, specialized equipment",
    link: "https://scholarships.gov.in/",
    Gender: "All",
    Cast: "All",
    EducationLevel: "Postgraduate",
  },
  {
    id: 37,
    Name: "Innovation Scholarship",
    Benefits: "Tuition, innovation grant",
    link: "https://scholarships.gov.in/",
    Gender: "Female",
    Cast: "General",
    EducationLevel: "Higher Education",
  },
  {
    id: 38,
    Name: "Entrepreneurship Scholarship",
    Benefits: "Tuition, business mentorship",
    link: "https://scholarships.gov.in/",
    Gender: "Male",
    Cast: "OBC",
    EducationLevel: "Postgraduate",
  },
  {
    id: 39,
    Name: "Community Service Scholarship",
    Benefits: "Tuition and community project grant",
    link: "https://scholarships.gov.in/",
    Gender: "All",
    Cast: "ST",
    EducationLevel: "Diploma",
  },
  {
    id: 40,
    Name: "Future Leaders Scholarship",
    Benefits: "Stipend, leadership training",
    link: "https://scholarships.gov.in/",
    Gender: "Male",
    Cast: "General",
    EducationLevel: "Postgraduate",
  },
  {
    id: 41,
    Name: "Healthcare Workers Scholarship",
    Benefits: "Tuition, stipend",
    link: "https://scholarships.gov.in/",
    Gender: "Female",
    Cast: "SC",
    EducationLevel: "Undergraduate",
  },
  {
    id: 42,
    Name: "Veterans Scholarship",
    Benefits: "Tuition and maintenance",
    link: "https://scholarships.gov.in/",
    Gender: "Male",
    Cast: "OBC",
    EducationLevel: "Postgraduate",
  },
  {
    id: 43,
    Name: "Global Scholars Program",
    Benefits: "Full tuition and living allowance",
    link: "https://scholarships.gov.in/",
    Gender: "All",
    Cast: "General",
    EducationLevel: "Higher Education",
  },
  {
    id: 44,
    Name: "Renewable Energy Scholarship",
    Benefits: "Tuition and environmental research funding",
    link: "https://scholarships.gov.in/",
    Gender: "Male",
    Cast: "OBC",
    EducationLevel: "Diploma",
  },
  {
    id: 45,
    Name: "Financial Assistance for Girls",
    Benefits: "Tuition and living expenses",
    link: "https://scholarships.gov.in/",
    Gender: "Female",
    Cast: "All",
    EducationLevel: "School",
  },
  {
    id: 46,
    Name: "Literature Scholarship",
    Benefits: "Books and tuition fees",
    link: "https://scholarships.gov.in/",
    Gender: "Male",
    Cast: "SC",
    EducationLevel: "Postgraduate",
  },
  {
    id: 47,
    Name: "STEM Scholarship",
    Benefits: "Tuition and STEM-related funding",
    link: "https://scholarships.gov.in/",
    Gender: "Female",
    Cast: "ST",
    EducationLevel: "Undergraduate",
  },
  {
    id: 48,
    Name: "Health and Wellness Scholarship",
    Benefits: "Tuition, wellness support",
    link: "https://scholarships.gov.in/",
    Gender: "Male",
    Cast: "OBC",
    EducationLevel: "Postgraduate",
  },
  {
    id: 49,
    Name: "Cultural Exchange Scholarship",
    Benefits: "Funding for international programs",
    link: "https://scholarships.gov.in/",
    Gender: "All",
    Cast: "General",
    EducationLevel: "Higher Education",
  },
  {
    id: 50,
    Name: "Art and Design Scholarship",
    Benefits: "Tuition, art supplies",
    link: "https://scholarships.gov.in/",
    Gender: "Female",
    Cast: "SC",
    EducationLevel: "Undergraduate",
  },
  {
    id: 51,
    Name: "Comprehensive Scholarship",
    Benefits: "Covers all educational expenses",
    link: "https://scholarships.gov.in/",
    Gender: "All",
    Cast: "All",
    EducationLevel: "All",
  },
  {
    id: 52,
    Name: "General Merit Scholarship",
    Benefits: "Tuition and maintenance",
    link: "https://scholarships.gov.in/",
    Gender: "Male",
    Cast: "General",
    EducationLevel: "Undergraduate",
  },
  {
    id: 53,
    Name: "Women's Scholarship Program",
    Benefits: "Tuition and stipend",
    link: "https://scholarships.gov.in/",
    Gender: "Female",
    Cast: "General",
    EducationLevel: "Postgraduate",
  },
  {
    id: 54,
    Name: "Special Category Scholarship",
    Benefits: "Full fee waiver",
    link: "https://scholarships.gov.in/",
    Gender: "Male",
    Cast: "OBC",
    EducationLevel: "Diploma",
  },
  {
    id: 55,
    Name: "Educational Equity Scholarship",
    Benefits: "Books and tuition fees",
    link: "https://scholarships.gov.in/",
    Gender: "All",
    Cast: "SC",
    EducationLevel: "Higher Education",
  },
  {
    id: 56,
    Name: "ST Community Scholarship",
    Benefits: "Living expenses and books",
    link: "https://scholarships.gov.in/",
    Gender: "Male",
    Cast: "ST",
    EducationLevel: "School",
  },
  {
    id: 57,
    Name: "Inclusive Scholarship",
    Benefits: "Covers all expenses",
    link: "https://scholarships.gov.in/",
    Gender: "Female",
    Cast: "All",
    EducationLevel: "Diploma",
  },
  {
    id: 58,
    Name: "Leadership Scholarship",
    Benefits: "Full tuition support",
    link: "https://scholarships.gov.in/",
    Gender: "Male",
    Cast: "General",
    EducationLevel: "Postgraduate",
  },
  {
    id: 59,
    Name: "OBC Education Support",
    Benefits: "Books and living allowance",
    link: "https://scholarships.gov.in/",
    Gender: "Male",
    Cast: "OBC",
    EducationLevel: "Undergraduate",
  },
  {
    id: 60,
    Name: "SC Empowerment Grant",
    Benefits: "Tuition fee waiver",
    link: "https://scholarships.gov.in/",
    Gender: "Female",
    Cast: "SC",
    EducationLevel: "School",
  },
  {
    id: 61,
    Name: "ST Education Assistance",
    Benefits: "Full academic support",
    link: "https://scholarships.gov.in/",
    Gender: "All",
    Cast: "ST",
    EducationLevel: "Postgraduate",
  },
  {
    id: 62,
    Name: "General Scholarship Program",
    Benefits: "Tuition and books",
    link: "https://scholarships.gov.in/",
    Gender: "All",
    Cast: "General",
    EducationLevel: "Higher Education",
  },

  {
    id: 63,
    Name: "General Scholarship Program",
    Benefits: "Tuition and books",
    link: "https://scholarships.gov.in/",
    Gender: "Female",
    Cast: "ST",
    EducationLevel: "School",
  },

  {
    id: 64,
    Name: "General Scholarship Program",
    Benefits: "Tuition and books",
    link: "https://scholarships.gov.in/",
    Gender: "Female",
    Cast: "OBC",
    EducationLevel: "Undergraduate",
  },

  {
    id: 63,
    Name: "General Scholarship Program",
    Benefits: "Tuition and books",
    link: "https://scholarships.gov.in/",
    Gender: "Female",
    Cast: "OBC",
    EducationLevel: "Diploma",
  },
];
